//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl vygenerován nástrojem.
//
//     Změny v tomto souboru mohou způsobit nesprávné chování a budou ztraceny, pokud
//     bude kód vygenerován znovu. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Account {
    
    
    public partial class Confirm {
        
        /// <summary>
        /// Ovládací prvek successPanel
        /// </summary>
        /// <remarks>
        /// Automaticky generované pole.
        /// Pro úpravy přesuňte deklaraci pole ze souboru návrháře do souboru kódu na pozadí.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder successPanel;
        
        /// <summary>
        /// Ovládací prvek login
        /// </summary>
        /// <remarks>
        /// Automaticky generované pole.
        /// Pro úpravy přesuňte deklaraci pole ze souboru návrháře do souboru kódu na pozadí.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink login;
        
        /// <summary>
        /// Ovládací prvek errorPanel
        /// </summary>
        /// <remarks>
        /// Automaticky generované pole.
        /// Pro úpravy přesuňte deklaraci pole ze souboru návrháře do souboru kódu na pozadí.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder errorPanel;

    }
}
